management:
  endpoints:
    web:
      exposure:
        include: health,info

spring:
  application:
    name: hexlet-spring-blog
  datasource:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

app:
  welcome-message: "Welcome to Spring blog!"

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %5p [%X{correlationId:-}] --- %-40.40logger{39} : %m%n%wEx"

springdoc:
  paths-to-match: /api/**
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs